name: waiter_example
description: A Flutter project for full picker example.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  waiter:
    path: ../

  # Toast
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true