name: waiter_example
description: Demonstrates how to use the waiter plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  waiter:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true