name: waiter
description: A Flutter package to display loading indicators, error messages, and progress bars.
version: 1.0.7
homepage: https://github.com/mbfakourii/waiter
repository: https://github.com/mbfakourii/waiter
issue_tracker: https://github.com/mbfakourii/waiter/issues

topics:
  - waiter
  - loading
  - error
  - progress
  - retries

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Lottie
  lottie: ^3.1.0

  # Toast
  fluttertoast: ^8.2.4

  # Screenutil
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

screenshots:
  - description: Waiter logo.
    path: screenshots/logo.png