name: waiter
description: A Flutter package to display loading indicators, error messages, and progress bars.
version: 1.0.3
homepage: https://github.com/mbfakourii/waiter
issue_tracker: https://github.com/mbfakourii/waiter/issues
repository: https://github.com/mbfakourii/waiter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Lottie
  lottie: ^2.6.0

  # Toast
  fluttertoast: ^8.2.2

  # Screenutil
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  plugin:
    platforms:
      android:
        default_package: waiter
      ios:
        default_package: waiter
      linux:
        default_package: waiter
      macos:
        default_package: waiter
      web:
        default_package: waiter
      windows:
        default_package: waiter

screenshots:
  - description: Waiter logo.
    path: screenshots/logo.png