name: waiter
description: A Flutter package to display loading indicators, error messages, and progress bars.
version: 1.0.1
homepage: https://github.com/mbfakourii/waiter
issue_tracker: https://github.com/mbfakourii/waiter/issues
repository: https://github.com/mbfakourii/waiter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Lottie
  lottie: ^2.4.0

  # Toast
  fluttertoast: ^8.2.2

  # Sizer
  responsive_sizer: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  assets:
    - assets/

screenshots:
  - description: Waiter logo.
    path: screenshots/logo.png