name: waiter
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/mbfakourii/waiter
issue_tracker: https://github.com/mbfakourii/waiter/issues
repository: https://github.com/mbfakourii/waiter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

screenshots:
  - description: Waiter logo.
    path: screenshots/logo.png